# -*- coding: utf-8 -*-
"""E_152019049_TSABIT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ebBHgtuG6z1ivu2HGRLpUrYo1jz8P2l
"""

import pandas as pd

# 1. Fungsi untuk menghitung peningkatan gaji sebesar 5%
def hitung_gaji_setelah_peningkatan(gaji_sekarang):
    return gaji_sekarang * 1.05  # Peningkatan sebesar 5%

# Dataset
data = {'Nama': ['John', 'Jane', 'Bob', 'Alice'],
        'Usia': [25, 35, 30, 28],
        'Gaji': [50000, 60000, 70000, 55000]}

# DataFrame
df = pd.DataFrame(data)

# 2. Menghitung gaji setelah peningkatan sebesar 5%
for i in range(len(df)):
    gaji_sekarang = df.at[i, 'Gaji']
    gaji_setelah_peningkatan = hitung_gaji_setelah_peningkatan(gaji_sekarang)
    df.at[i, 'Gaji'] = gaji_setelah_peningkatan

# Menampilkan DataFrame setelah peningkatan gaji 5%
print("DataFrame setelah peningkatan gaji 5%:")
print(df)

# 3. Menambahkan peningkatan gaji tambahan 2% untuk karyawan yang usianya di atas 30 tahun
df['Gaji'] = df.apply(lambda row: row['Gaji'] * 1.02 if row['Usia'] > 30 else row['Gaji'], axis=1)

# 4. Menampilkan DataFrame setelah peningkatan gaji tambahan
print("\nDataFrame setelah peningkatan gaji tambahan:")
print(df)

# Ringkasan perubahan
print("\nRingkasan Perubahan:")
for i in range(len(df)):
    print(f"{df.at[i, 'Nama']}: Gaji sebelumnya {data['Gaji'][i]}, Gaji setelah peningkatan 5% {hitung_gaji_setelah_peningkatan(data['Gaji'][i])}, Gaji setelah peningkatan tambahan 2% {df.at[i, 'Gaji']}")